# Generated by Django 5.0.4 on 2024-04-21 19:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_created_remove_user_ref_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated_invite_codes',
        ),
        migrations.AddField(
            model_name='user',
            name='activated_invite_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
