# Generated by Django 5.0.4 on 2024-04-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_activated_invite_codes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activated_invite_codes',
            new_name='numbers_activated_invite_codes',
        ),
    ]
