# Generated by Django 5.0.4 on 2024-04-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_numbers_activated_invite_codes_user_numbers_activated_invite_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activated_invite_codes',
            new_name='activated_invite_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='numbers_activated_invite_code',
            new_name='numbers_activated_invite_codes',
        ),
    ]
