# Generated by Django 5.0.4 on 2024-04-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_activated_invite_codes_user_activated_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated_invite_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
